### PR TITLE
Issue/accessibility

### PR DESCRIPTION
**Pull request by cayb0rg**
Begins the syntax sorter accessibility revamp for the Player.

Changes made
- Adds keyboard navigation to tokens and adds the instructions for the controls to the tutorial. Right now, it is using Click, Space or Enter to move tokens into and out of the sorting area (in addition to Right Click for moving tokens out), and Q and E to move the token left or right in the sorting area.
- Adds focus styling
- Uses HTML semantics and aria landmarks (as opposed to just ``div`` and ``span`` elements)
- Makes hint-text hidden-hidden (not just opacity: 0)
- Adds aria-labels such as "Question 1" and "Question 2"
- Announces question submission result to screenreader (``aria-describedby`` on button)
- Wraps question buttons in a ``<nav>``
- Announces legend type on focus of token (right now, color is the only indicator). This could be done by ``aria-describedby`` or ``aria-label``. Doesn't read label if meant to use Legend descriptor only.
- Changes Submit and Tutorial button styling so they are read in correct order
- Warning modal when submitting is focused on popup
- Redirects focus on Check Question or Next Question correctly

This also upgrades babel and adds the plugins [eslint-plugin-jsx-a11y](https://www.npmjs.com/package/eslint-plugin-jsx-a11y) and [react-axe](https://www.npmjs.com/package/react-axe) for development. Run ``yarn install`` to update.

Issues/Concerns
- ~~Currently, pressing Ctrl+Option+Space in VoiceOver does not move the token~~

### CODE REVIEW

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
This a REALLY GOOD initial implementation. A few things that stood out to me or that I'd like to see:

- Several elements are part of the tab index that probably shouldn't be, like the question text, and the response dialog text accompanying the Check Answer and Next Question buttons. Navigation with VO + left/right keys can access those elements already. For the case of the question, it may be useful to provide some additional information to clarify that this is the question text, but I'm not 100% certain how best to indicate that. The response dialog appears to already be served when the Check Answer button is focused, but it might also be helpful to indicate game state through a live region when a token is sorted or moved ("all tokens sorted", "X of Y tokens sorted", that sort of thing)
- Similar to the above, since the tokens aren't really _buttons_, it'd be potentially useful to have live region updates when a token is sorted or unsorted to provide immediate feedback on what operation was performed
- A key to read the current phrase as it is assembled would be super useful
- Potentially add additional status information appended to question buttons to indicate whether the selection question is complete or incomplete when the button is focused
- Add status information when focusing the submit answer button to indicate how many questions are incomplete, and which ones
- I'm getting several console errors in the player, related to unidentified aria props (`aria-model`), use of `tabindex` instead of `tabIndex`, and list items not being given a unique `key` property

**Comment by cayb0rg** [comment]
These are some great recommendations, thank you! I may have to do the status updates a little differently, but I think they achieve the same goal.
- I removed the tab-index from those elements. Sending focus to the question text after hitting Next Question could be confusing. I also added "Question" in the aria-label for the heading, but it still appears to read out the inner text before the label.
- I'm unable to use live region updates for things such as token sorting or checking answers because element focusing overrides it (whether aria-live is set to "assertive" or "polite"). However, I think your suggestion of using a key to read out the current phrase would be sufficient enough in making the user aware of the game's current state.
- I worry about using "all tokens sorted" or "X of Y tokens sorted" as that might suggest they all need to be sorted, but this is not always the case with fake tokens.
- Adding status information to the questions as well as submit button is a good idea! I've added attempts remaining to the info as well.

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
Great work. LGTM, you might just have to update the test snapshots again since they're not passing and remove the `.DS_Store` file under `src/assets/` :+1: Once that's done, I'll approve and merge.

**Review by clpetersonucf — APPROVED** [review]
LGTM :+1: I couldn't figure out why the snapshot tests were failing to pass despite being updated, so I temporarily turned them off in the GH workflow.

Nice work :+1:

**Pull request merged**
